'use strict';

/** Catálogo canônico de notificações (Sprint 28.2). Cresce sem inventar disparos. */
const NOTIFICATION_TYPES = Object.freeze({
  REQUEST_MESSAGE: 'REQUEST_MESSAGE',
  REQUEST_CREATED: 'REQUEST_CREATED',

  DOCUMENT_RECEIVED: 'DOCUMENT_RECEIVED',
  DOCUMENT_ANALYSIS_COMPLETED: 'DOCUMENT_ANALYSIS_COMPLETED',
  DOCUMENT_ANALYSIS_FAILED: 'DOCUMENT_ANALYSIS_FAILED',

  EXPENSE_RECEIVED: 'EXPENSE_RECEIVED',
  EXPENSE_CREATED: 'EXPENSE_CREATED',
  EXPENSE_UPDATED: 'EXPENSE_UPDATED',

  REVENUE_RECEIVED: 'REVENUE_RECEIVED',
  REVENUE_CREATED: 'REVENUE_CREATED',

  CLASSIFICATION_PENDING: 'CLASSIFICATION_PENDING',
  CLASSIFICATION_COMPLETED: 'CLASSIFICATION_COMPLETED',

  APPROVAL_PENDING: 'APPROVAL_PENDING',
  APPROVAL_COMPLETED: 'APPROVAL_COMPLETED',
  APPROVAL_REJECTED: 'APPROVAL_REJECTED',

  ENTRY_CREATED: 'ENTRY_CREATED',
  ENTRY_UPDATED: 'ENTRY_UPDATED',
  ENTRY_POSTED: 'ENTRY_POSTED',

  PROCESS_CREATED: 'PROCESS_CREATED',
  PROCESS_STEP_DUE: 'PROCESS_STEP_DUE',
  PROCESS_STEP_OVERDUE: 'PROCESS_STEP_OVERDUE',
  PROCESS_COMPLETED: 'PROCESS_COMPLETED',

  INTEGRATION_COMPLETED: 'INTEGRATION_COMPLETED',
  INTEGRATION_FAILED: 'INTEGRATION_FAILED',

  PENDENCY_CREATED: 'PENDENCY_CREATED',
  PENDENCY_UPDATED: 'PENDENCY_UPDATED',

  PUSH_TEST: 'PUSH_TEST'
});

/** Preferência de canal/categoria em user_notification_prefs */
const PREF_KEYS = Object.freeze({
  requests: 'requests_enabled',
  documents: 'documents_enabled',
  expenses: 'expenses_enabled',
  classification: 'classification_enabled',
  approval: 'approval_enabled',
  processes: 'processes_enabled',
  integrations: 'integrations_enabled',
  push: 'push_enabled',
  visual: 'visual_enabled',
  sound: 'sound_enabled'
});

const TYPE_PREF = Object.freeze({
  [NOTIFICATION_TYPES.REQUEST_MESSAGE]: PREF_KEYS.requests,
  [NOTIFICATION_TYPES.REQUEST_CREATED]: PREF_KEYS.requests,
  [NOTIFICATION_TYPES.DOCUMENT_RECEIVED]: PREF_KEYS.documents,
  [NOTIFICATION_TYPES.DOCUMENT_ANALYSIS_COMPLETED]: PREF_KEYS.documents,
  [NOTIFICATION_TYPES.DOCUMENT_ANALYSIS_FAILED]: PREF_KEYS.documents,
  [NOTIFICATION_TYPES.EXPENSE_RECEIVED]: PREF_KEYS.expenses,
  [NOTIFICATION_TYPES.EXPENSE_CREATED]: PREF_KEYS.expenses,
  [NOTIFICATION_TYPES.EXPENSE_UPDATED]: PREF_KEYS.expenses,
  [NOTIFICATION_TYPES.REVENUE_RECEIVED]: PREF_KEYS.expenses,
  [NOTIFICATION_TYPES.REVENUE_CREATED]: PREF_KEYS.expenses,
  [NOTIFICATION_TYPES.CLASSIFICATION_PENDING]: PREF_KEYS.classification,
  [NOTIFICATION_TYPES.CLASSIFICATION_COMPLETED]: PREF_KEYS.classification,
  [NOTIFICATION_TYPES.APPROVAL_PENDING]: PREF_KEYS.approval,
  [NOTIFICATION_TYPES.APPROVAL_COMPLETED]: PREF_KEYS.approval,
  [NOTIFICATION_TYPES.APPROVAL_REJECTED]: PREF_KEYS.approval,
  [NOTIFICATION_TYPES.ENTRY_CREATED]: PREF_KEYS.classification,
  [NOTIFICATION_TYPES.ENTRY_UPDATED]: PREF_KEYS.classification,
  [NOTIFICATION_TYPES.ENTRY_POSTED]: PREF_KEYS.approval,
  [NOTIFICATION_TYPES.PROCESS_CREATED]: PREF_KEYS.processes,
  [NOTIFICATION_TYPES.PROCESS_STEP_DUE]: PREF_KEYS.processes,
  [NOTIFICATION_TYPES.PROCESS_STEP_OVERDUE]: PREF_KEYS.processes,
  [NOTIFICATION_TYPES.PROCESS_COMPLETED]: PREF_KEYS.processes,
  [NOTIFICATION_TYPES.INTEGRATION_COMPLETED]: PREF_KEYS.integrations,
  [NOTIFICATION_TYPES.INTEGRATION_FAILED]: PREF_KEYS.integrations,
  [NOTIFICATION_TYPES.PENDENCY_CREATED]: PREF_KEYS.requests,
  [NOTIFICATION_TYPES.PENDENCY_UPDATED]: PREF_KEYS.requests,
  [NOTIFICATION_TYPES.PUSH_TEST]: PREF_KEYS.push
});

/**
 * Mapeia event_type de domain_events → tipo canônico de notificação.
 * Ausência = sem push automático pelo motor (ainda pode ter in-app legado).
 */
const DOMAIN_TO_NOTIFICATION = Object.freeze({
  REQUEST_CREATED: NOTIFICATION_TYPES.REQUEST_CREATED,
  REQUEST_MESSAGE_CREATED: NOTIFICATION_TYPES.REQUEST_MESSAGE,
  REQUEST_UPDATED: NOTIFICATION_TYPES.REQUEST_MESSAGE,
  DOCUMENT_UPLOADED: NOTIFICATION_TYPES.DOCUMENT_RECEIVED,
  EXPENSE_CREATED: NOTIFICATION_TYPES.EXPENSE_RECEIVED,
  REVENUE_CREATED: NOTIFICATION_TYPES.REVENUE_RECEIVED,
  CLASSIFICATION_REQUIRED: NOTIFICATION_TYPES.CLASSIFICATION_PENDING,
  CLASSIFICATION_COMPLETED: NOTIFICATION_TYPES.CLASSIFICATION_COMPLETED,
  ENTRY_CREATED: NOTIFICATION_TYPES.ENTRY_CREATED,
  APPROVAL_REQUIRED: NOTIFICATION_TYPES.APPROVAL_PENDING,
  ENTRY_APPROVED: NOTIFICATION_TYPES.APPROVAL_COMPLETED,
  ENTRY_POSTED: NOTIFICATION_TYPES.ENTRY_POSTED,
  ENTRY_REJECTED: NOTIFICATION_TYPES.APPROVAL_REJECTED,
  IMPORT_COMPLETED: NOTIFICATION_TYPES.INTEGRATION_COMPLETED,
  IMPORT_FAILED: NOTIFICATION_TYPES.INTEGRATION_FAILED,
  PENDENCY_RESPONSE: NOTIFICATION_TYPES.PENDENCY_UPDATED,
  PROCESS_OCCURRENCE_AUTO_CREATED: NOTIFICATION_TYPES.PROCESS_CREATED,
  PROCESS_OCCURRENCE_MANUALLY_CREATED: NOTIFICATION_TYPES.PROCESS_CREATED,
  PROCESS_STEP_OVERDUE: NOTIFICATION_TYPES.PROCESS_STEP_OVERDUE,
  PROCESS_OCCURRENCE_COMPLETED: NOTIFICATION_TYPES.PROCESS_COMPLETED
});

/** Tipos cujo push já é disparado pelo fluxo de Solicitações (evitar duplicar). */
const SKIP_DOMAIN_PUSH = new Set([
  'REQUEST_MESSAGE_CREATED',
  'REQUEST_UPDATED',
  'REQUEST_CREATED',
  'REQUEST_STATUS_CHANGED',
  'REQUEST_MESSAGE_READ'
]);

/** Tipos de domínio que disparam Web Push via NotificationService. */
const DOMAIN_PUSH_TYPES = new Set(
  Object.keys(DOMAIN_TO_NOTIFICATION).filter((k) => !SKIP_DOMAIN_PUSH.has(k))
);

function isKnownType(type) {
  return Object.prototype.hasOwnProperty.call(NOTIFICATION_TYPES, type)
    || Object.values(NOTIFICATION_TYPES).includes(type);
}

function prefKeyForType(type) {
  return TYPE_PREF[type] || PREF_KEYS.requests;
}

function fromDomainEvent(eventType) {
  return DOMAIN_TO_NOTIFICATION[eventType] || null;
}

module.exports = {
  NOTIFICATION_TYPES,
  PREF_KEYS,
  TYPE_PREF,
  DOMAIN_TO_NOTIFICATION,
  SKIP_DOMAIN_PUSH,
  DOMAIN_PUSH_TYPES,
  isKnownType,
  prefKeyForType,
  fromDomainEvent
};
