'use strict';

/** Categorias oficiais Audácia Contabilidade Estratégica — não criar nomes paralelos. */
const OPERATION_TYPES = Object.freeze({
  COMPRA: 'COMPRA',
  VENDA: 'VENDA',
  SERVICO_TOMADO: 'SERVIÇO TOMADO',
  SERVICO_PRESTADO: 'SERVIÇO PRESTADO',
  DESPESA: 'DESPESA',
  RECEITA: 'RECEITA',
  PAGAMENTO: 'PAGAMENTO',
  RECEBIMENTO: 'RECEBIMENTO',
  FOLHA: 'FOLHA',
  PRO_LABORE: 'PRÓ-LABORE',
  IMPOSTO: 'IMPOSTO',
  FINANCIAMENTO: 'FINANCIAMENTO',
  EMPRESTIMO: 'EMPRÉSTIMO',
  ATIVO_IMOBILIZADO: 'ATIVO IMOBILIZADO',
  TRANSFERENCIA_BANCARIA: 'TRANSFERÊNCIA BANCÁRIA',
  TARIFA_BANCARIA: 'TARIFA BANCÁRIA',
  OUTROS: 'OUTROS'
});

const OPERATION_TYPE_LIST = Object.freeze(Object.values(OPERATION_TYPES));

const OPERATION_TYPE_SET = new Set(OPERATION_TYPE_LIST);

/** Mapeia natureza → kind EXPENSE/REVENUE para o motor CDS. */
const OPERATION_KIND = Object.freeze({
  [OPERATION_TYPES.COMPRA]: 'EXPENSE',
  [OPERATION_TYPES.VENDA]: 'REVENUE',
  [OPERATION_TYPES.SERVICO_TOMADO]: 'EXPENSE',
  [OPERATION_TYPES.SERVICO_PRESTADO]: 'REVENUE',
  [OPERATION_TYPES.DESPESA]: 'EXPENSE',
  [OPERATION_TYPES.RECEITA]: 'REVENUE',
  [OPERATION_TYPES.PAGAMENTO]: 'EXPENSE',
  [OPERATION_TYPES.RECEBIMENTO]: 'REVENUE',
  [OPERATION_TYPES.FOLHA]: 'EXPENSE',
  [OPERATION_TYPES.PRO_LABORE]: 'EXPENSE',
  [OPERATION_TYPES.IMPOSTO]: 'EXPENSE',
  [OPERATION_TYPES.FINANCIAMENTO]: 'EXPENSE',
  [OPERATION_TYPES.EMPRESTIMO]: 'EXPENSE',
  [OPERATION_TYPES.ATIVO_IMOBILIZADO]: 'EXPENSE',
  [OPERATION_TYPES.TRANSFERENCIA_BANCARIA]: 'EXPENSE',
  [OPERATION_TYPES.TARIFA_BANCARIA]: 'EXPENSE',
  [OPERATION_TYPES.OUTROS]: 'EXPENSE'
});

function normalizeOperationType(raw) {
  const s = String(raw || '').trim().toUpperCase()
    .normalize('NFD').replace(/[\u0300-\u036f]/g, '');
  if (!s) return null;
  const aliases = {
    'COMPRA': OPERATION_TYPES.COMPRA,
    'VENDA': OPERATION_TYPES.VENDA,
    'SERVICO TOMADO': OPERATION_TYPES.SERVICO_TOMADO,
    'SERVICO PRESTADO': OPERATION_TYPES.SERVICO_PRESTADO,
    'DESPESA': OPERATION_TYPES.DESPESA,
    'RECEITA': OPERATION_TYPES.RECEITA,
    'PAGAMENTO': OPERATION_TYPES.PAGAMENTO,
    'RECEBIMENTO': OPERATION_TYPES.RECEBIMENTO,
    'FOLHA': OPERATION_TYPES.FOLHA,
    'PRO-LABORE': OPERATION_TYPES.PRO_LABORE,
    'PRO LABORE': OPERATION_TYPES.PRO_LABORE,
    'IMPOSTO': OPERATION_TYPES.IMPOSTO,
    'FINANCIAMENTO': OPERATION_TYPES.FINANCIAMENTO,
    'EMPRESTIMO': OPERATION_TYPES.EMPRESTIMO,
    'ATIVO IMOBILIZADO': OPERATION_TYPES.ATIVO_IMOBILIZADO,
    'TRANSFERENCIA BANCARIA': OPERATION_TYPES.TRANSFERENCIA_BANCARIA,
    'TARIFA BANCARIA': OPERATION_TYPES.TARIFA_BANCARIA,
    'OUTROS': OPERATION_TYPES.OUTROS,
    'EXPENSE': OPERATION_TYPES.DESPESA,
    'REVENUE': OPERATION_TYPES.RECEITA,
    'OTHER': OPERATION_TYPES.OUTROS
  };
  if (aliases[s]) return aliases[s];
  if (OPERATION_TYPE_SET.has(String(raw || '').trim())) return String(raw).trim();
  return null;
}

function isValidOperationType(value) {
  return OPERATION_TYPE_SET.has(value);
}

function kindOf(operationType) {
  return OPERATION_KIND[operationType] || 'EXPENSE';
}

module.exports = {
  OPERATION_TYPES,
  OPERATION_TYPE_LIST,
  OPERATION_TYPE_SET,
  OPERATION_KIND,
  normalizeOperationType,
  isValidOperationType,
  kindOf
};
