'use strict';

const {EVENT_TYPES}=require('../domain-events');

const COMMUNICATION_EVENTS=Object.freeze({
  USER_INVITE:'USER_INVITE',
  USER_INVITE_RESEND:'USER_INVITE_RESEND',
  PASSWORD_RESET:'PASSWORD_RESET',
  EMAIL_TEST:'EMAIL_TEST',
  DOCUMENT_RECEIVED:'DOCUMENT_UPLOADED',
  EXPENSE_RECEIVED:'EXPENSE_CREATED',
  REQUEST_CREATED:'REQUEST_CREATED',
  PENDING_CREATED:'PENDENCY_RESPONSE',
  ACCOUNTING_REVIEW_REQUIRED:'CLASSIFICATION_REQUIRED',
  ...EVENT_TYPES
});

const EVENT_LABELS=Object.freeze({
  USER_INVITE:'Convite de acesso',
  USER_INVITE_RESEND:'Reenvio de convite',
  PASSWORD_RESET:'Redefinição de senha',
  EMAIL_TEST:'E-mail de teste',
  EXPENSE_CREATED:'Nova despesa',
  DOCUMENT_UPLOADED:'Novo documento',
  REQUEST_CREATED:'Nova solicitação',
  CLASSIFICATION_REQUIRED:'Classificação pendente',
  REVENUE_CREATED:'Nova receita'
});

const OFFICE_EMAIL_EVENTS=new Set([
  COMMUNICATION_EVENTS.EXPENSE_CREATED,
  COMMUNICATION_EVENTS.DOCUMENT_UPLOADED,
  COMMUNICATION_EVENTS.CLASSIFICATION_REQUIRED,
  COMMUNICATION_EVENTS.REQUEST_CREATED
]);

function eventLabel(type){
  return EVENT_LABELS[type]||type||'Comunicação';
}

module.exports={COMMUNICATION_EVENTS,EVENT_LABELS,OFFICE_EMAIL_EVENTS,eventLabel};
